name: Convert AAB to APK
on:
  workflow_dispatch: # Permette di avviarlo manualmente con un tasto

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Bundletool
        run: |
          wget https://github.com/google/bundletool/releases/download/1.17.0/bundletool-all-1.17.0.jar -O bundletool.jar

      - name: Download AAB from GitHub Release
        run: |
          # Incolla il link che hai appena copiato tra le virgolette
          curl -L "https://www.dropbox.com/scl/fi/86klps6xevkgtu4ak3ins/app-release.aab?rlkey=1ui29jvd2tq25ax7g1k4mdbz1&st=9cbjqj4p&dl=0" -o app-release.aab
          
          # Verifica che sia 64MB
          ls -lh app-release.aab

      - name: Convert AAB to Universal APK
        run: |
          # Cancella eventuali file residui da build fallite o precedenti
          rm -f app.apks
          rm -rf extracted_apk
          
          java -jar bundletool.jar build-apks \
            --bundle=app-release.aab \
            --output=app.apks \
            --mode=universal

      - name: Extract APK
        run: |
          unzip app.apks -d extracted_apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: extracted_apk/universal.apk
          
      - name: Download AAB from Expo
        run: |
          # Incolla il link tra le virgolette
          wget "https://expo.dev/artifacts/eas/hY1iEd3VcsB2PNFZiDaTSh.aab" -O app-release.aab

      - name: Convert AAB to Universal APK
        run: |
          java -jar bundletool.jar build-apks \
            --bundle=app-release.aab \
            --output=app.apks \
            --mode=universal

      - name: Extract APK
        run: |
          unzip app.apks -d extracted_apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: extracted_apk/universal.apk
