name: Convert AAB to APK
on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Bundletool
        run: |
          wget https://github.com/google/bundletool/releases/download/1.17.0/bundletool-all-1.17.0.jar -O bundletool.jar

      - name: Download AAB from Dropbox
        run: |
          # Download diretto forzato con dl=1
          curl -L "https://www.dropbox.com/scl/fi/86klps6xevkgtu4ak3ins/app-release.aab?rlkey=1ui29jvd2tq25ax7g1k4mdbz1&st=9cbjqj4p&dl=1" -o app-release.aab
          ls -lh app-release.aab

      - name: Convert AAB to Universal APK
        run: |
          rm -f app.apks
          rm -rf extracted_apk
          
          # Creiamo una chiave di debug al volo per firmare l'APK
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

          # Usiamo la chiave per firmare l'output di bundletool
          java -jar bundletool.jar build-apks \
            --bundle=app-release.aab \
            --output=app.apks \
            --mode=universal \
            --local-testing \
            --ks=debug.keystore \
            --ks-pass=pass:android \
            --ks-key-alias=androiddebugkey \
            --key-pass=pass:android

      - name: Extract APK
        run: |
          unzip app.apks -d extracted_apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk-signed
          path: extracted_apk/universal.apk
